json.id ark.id
json.description ark.description 
json.created_at ark.created_at 
json.serial_num ark.serial_num 
json.completed ark.completed 
json.user_id ark.user_id
json.image ark.image
json.location ark.location
json.user ark.user